name: "Build and Test"
on:
  pull_request:
    paths-ignore:
      - '*.md'
    types:
      - synchronize
      - opened
jobs:
  review:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '19'
          cache: gradle
      - name: Setup docker (MacOS only)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start

          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: Launch Autobahn Test Suite Docker Image (MacOS only)
        if: runner.os == 'macos'
        run: |
          docker run -it --rm -v "${PWD}/.docker/config:/config" -v "${PWD}/.docker/reports:/reports" -p 9001:9001 --name fuzzingserver crossbario/autobahn-testsuite
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Tests with Gradle
        run: ./gradlew ktlintCheck assemble build check allTests publishToMavenLocal
